require("config.after.telescope")
require("config.after.treesitter")
require("config.after.lsp")
require("config.after.lualine")
require("config.after.conform")
require("config.after.alpha")
require("config.after.indent-blankline")
require("config.after.luasnip")
